project:
  type: website
  output-dir: docs
  preview:
    port: 4000
    host: 0.0.0.0
    browser: false
    
bibliography: references.bib

website:
  title: "EPC Capsule"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Narrative
      - data_acquisition.ipynb
      - gpu_spatial_join.ipynb
      - href: analysis.ipynb
        text: Analysis
      - href: about.qmd
        text: About

format:
  html:
    theme: journal
    css: styles.css
    toc: true


